{{- range $env, $regions := .Values.cloud }}
{{- if or (eq $env $.Values.env) (eq $.Values.env "all") }}
{{- range $region, $scope := $regions }}
{{- if or (eq $region $.Values.region) (eq $.Values.region "all") }}
{{- if default $.Values.default.serviceAccount.create ( $scope.serviceAccount ).create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-test.serviceAccountName" $ }}
  labels:
    {{- include "prometheus-test.labels" $ | nindent 4 }}
  {{- with default $.Values.default.serviceAccount.annotations ( $scope.serviceAccount ).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ printf "\n" }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
